vendor: Cisco Systems
name: Zot
version: v1.4.1
website_url: https://zotregistry.io/
repo_url: https://github.com/project-zot/zot
documentation_url: https://github.com/project-zot/zot
product_logo_url: https://avatars.githubusercontent.com/u/33209725
type: distribution
description: A vendor-neutral OCI image registry server purely based on OCI Distribution Specification
